//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("LabRestauranteModel", "fk_DetalleFactura_Bebida", "Bebida", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CadRestaurante.Bebida), "DetalleFactura", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CadRestaurante.DetalleFactura), true)]
[assembly: EdmRelationshipAttribute("LabRestauranteModel", "fk_DetalleFactura_Cliente", "Cliente", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CadRestaurante.Cliente), "DetalleFactura", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CadRestaurante.DetalleFactura), true)]
[assembly: EdmRelationshipAttribute("LabRestauranteModel", "fk_DetalleFactura_Comida", "Comida", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CadRestaurante.Comida), "DetalleFactura", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CadRestaurante.DetalleFactura), true)]
[assembly: EdmRelationshipAttribute("LabRestauranteModel", "fk_DetalleFactura_Empleado", "Empleado", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CadRestaurante.Empleado), "DetalleFactura", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CadRestaurante.DetalleFactura), true)]
[assembly: EdmRelationshipAttribute("LabRestauranteModel", "fk_Usuario_Empleado", "Empleado", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CadRestaurante.Empleado), "Usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CadRestaurante.Usuario), true)]

#endregion

namespace CadRestaurante
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class LabRestauranteEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto LabRestauranteEntities usando la cadena de conexión encontrada en la sección 'LabRestauranteEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public LabRestauranteEntities() : base("name=LabRestauranteEntities", "LabRestauranteEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto LabRestauranteEntities.
        /// </summary>
        public LabRestauranteEntities(string connectionString) : base(connectionString, "LabRestauranteEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto LabRestauranteEntities.
        /// </summary>
        public LabRestauranteEntities(EntityConnection connection) : base(connection, "LabRestauranteEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Bebida> Bebida
        {
            get
            {
                if ((_Bebida == null))
                {
                    _Bebida = base.CreateObjectSet<Bebida>("Bebida");
                }
                return _Bebida;
            }
        }
        private ObjectSet<Bebida> _Bebida;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Cliente> Cliente
        {
            get
            {
                if ((_Cliente == null))
                {
                    _Cliente = base.CreateObjectSet<Cliente>("Cliente");
                }
                return _Cliente;
            }
        }
        private ObjectSet<Cliente> _Cliente;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Comida> Comida
        {
            get
            {
                if ((_Comida == null))
                {
                    _Comida = base.CreateObjectSet<Comida>("Comida");
                }
                return _Comida;
            }
        }
        private ObjectSet<Comida> _Comida;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<DetalleFactura> DetalleFactura
        {
            get
            {
                if ((_DetalleFactura == null))
                {
                    _DetalleFactura = base.CreateObjectSet<DetalleFactura>("DetalleFactura");
                }
                return _DetalleFactura;
            }
        }
        private ObjectSet<DetalleFactura> _DetalleFactura;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Empleado> Empleado
        {
            get
            {
                if ((_Empleado == null))
                {
                    _Empleado = base.CreateObjectSet<Empleado>("Empleado");
                }
                return _Empleado;
            }
        }
        private ObjectSet<Empleado> _Empleado;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Usuario> Usuario
        {
            get
            {
                if ((_Usuario == null))
                {
                    _Usuario = base.CreateObjectSet<Usuario>("Usuario");
                }
                return _Usuario;
            }
        }
        private ObjectSet<Usuario> _Usuario;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Bebida. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToBebida(Bebida bebida)
        {
            base.AddObject("Bebida", bebida);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Cliente. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToCliente(Cliente cliente)
        {
            base.AddObject("Cliente", cliente);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Comida. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToComida(Comida comida)
        {
            base.AddObject("Comida", comida);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet DetalleFactura. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToDetalleFactura(DetalleFactura detalleFactura)
        {
            base.AddObject("DetalleFactura", detalleFactura);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Empleado. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToEmpleado(Empleado empleado)
        {
            base.AddObject("Empleado", empleado);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Usuario. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToUsuario(Usuario usuario)
        {
            base.AddObject("Usuario", usuario);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LabRestauranteModel", Name="Bebida")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Bebida : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Bebida.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="precio">Valor inicial de la propiedad precio.</param>
        /// <param name="descripcion">Valor inicial de la propiedad descripcion.</param>
        /// <param name="usuarioRegistro">Valor inicial de la propiedad usuarioRegistro.</param>
        /// <param name="fechaRegistro">Valor inicial de la propiedad fechaRegistro.</param>
        /// <param name="estado">Valor inicial de la propiedad estado.</param>
        public static Bebida CreateBebida(global::System.Int32 id, global::System.String nombre, global::System.Decimal precio, global::System.String descripcion, global::System.String usuarioRegistro, global::System.DateTime fechaRegistro, global::System.Int16 estado)
        {
            Bebida bebida = new Bebida();
            bebida.id = id;
            bebida.nombre = nombre;
            bebida.precio = precio;
            bebida.descripcion = descripcion;
            bebida.usuarioRegistro = usuarioRegistro;
            bebida.fechaRegistro = fechaRegistro;
            bebida.estado = estado;
            return bebida;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false, "nombre");
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal precio
        {
            get
            {
                return _precio;
            }
            set
            {
                OnprecioChanging(value);
                ReportPropertyChanging("precio");
                _precio = StructuralObject.SetValidValue(value, "precio");
                ReportPropertyChanged("precio");
                OnprecioChanged();
            }
        }
        private global::System.Decimal _precio;
        partial void OnprecioChanging(global::System.Decimal value);
        partial void OnprecioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String marca
        {
            get
            {
                return _marca;
            }
            set
            {
                OnmarcaChanging(value);
                ReportPropertyChanging("marca");
                _marca = StructuralObject.SetValidValue(value, true, "marca");
                ReportPropertyChanged("marca");
                OnmarcaChanged();
            }
        }
        private global::System.String _marca;
        partial void OnmarcaChanging(global::System.String value);
        partial void OnmarcaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, false, "descripcion");
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String usuarioRegistro
        {
            get
            {
                return _usuarioRegistro;
            }
            set
            {
                OnusuarioRegistroChanging(value);
                ReportPropertyChanging("usuarioRegistro");
                _usuarioRegistro = StructuralObject.SetValidValue(value, false, "usuarioRegistro");
                ReportPropertyChanged("usuarioRegistro");
                OnusuarioRegistroChanged();
            }
        }
        private global::System.String _usuarioRegistro;
        partial void OnusuarioRegistroChanging(global::System.String value);
        partial void OnusuarioRegistroChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fechaRegistro
        {
            get
            {
                return _fechaRegistro;
            }
            set
            {
                OnfechaRegistroChanging(value);
                ReportPropertyChanging("fechaRegistro");
                _fechaRegistro = StructuralObject.SetValidValue(value, "fechaRegistro");
                ReportPropertyChanged("fechaRegistro");
                OnfechaRegistroChanged();
            }
        }
        private global::System.DateTime _fechaRegistro;
        partial void OnfechaRegistroChanging(global::System.DateTime value);
        partial void OnfechaRegistroChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value, "estado");
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.Int16 _estado;
        partial void OnestadoChanging(global::System.Int16 value);
        partial void OnestadoChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LabRestauranteModel", "fk_DetalleFactura_Bebida", "DetalleFactura")]
        public EntityCollection<DetalleFactura> DetalleFactura
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DetalleFactura>("LabRestauranteModel.fk_DetalleFactura_Bebida", "DetalleFactura");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DetalleFactura>("LabRestauranteModel.fk_DetalleFactura_Bebida", "DetalleFactura", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LabRestauranteModel", Name="Cliente")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Cliente : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Cliente.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="primerApellido">Valor inicial de la propiedad primerApellido.</param>
        /// <param name="segundoApellido">Valor inicial de la propiedad segundoApellido.</param>
        /// <param name="cedulaIdentidad">Valor inicial de la propiedad cedulaIdentidad.</param>
        /// <param name="usuarioRegistro">Valor inicial de la propiedad usuarioRegistro.</param>
        /// <param name="fechaRegistro">Valor inicial de la propiedad fechaRegistro.</param>
        /// <param name="estado">Valor inicial de la propiedad estado.</param>
        public static Cliente CreateCliente(global::System.Int32 id, global::System.String nombre, global::System.String primerApellido, global::System.String segundoApellido, global::System.String cedulaIdentidad, global::System.String usuarioRegistro, global::System.DateTime fechaRegistro, global::System.Int16 estado)
        {
            Cliente cliente = new Cliente();
            cliente.id = id;
            cliente.nombre = nombre;
            cliente.primerApellido = primerApellido;
            cliente.segundoApellido = segundoApellido;
            cliente.cedulaIdentidad = cedulaIdentidad;
            cliente.usuarioRegistro = usuarioRegistro;
            cliente.fechaRegistro = fechaRegistro;
            cliente.estado = estado;
            return cliente;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false, "nombre");
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String primerApellido
        {
            get
            {
                return _primerApellido;
            }
            set
            {
                OnprimerApellidoChanging(value);
                ReportPropertyChanging("primerApellido");
                _primerApellido = StructuralObject.SetValidValue(value, false, "primerApellido");
                ReportPropertyChanged("primerApellido");
                OnprimerApellidoChanged();
            }
        }
        private global::System.String _primerApellido;
        partial void OnprimerApellidoChanging(global::System.String value);
        partial void OnprimerApellidoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String segundoApellido
        {
            get
            {
                return _segundoApellido;
            }
            set
            {
                OnsegundoApellidoChanging(value);
                ReportPropertyChanging("segundoApellido");
                _segundoApellido = StructuralObject.SetValidValue(value, false, "segundoApellido");
                ReportPropertyChanged("segundoApellido");
                OnsegundoApellidoChanged();
            }
        }
        private global::System.String _segundoApellido;
        partial void OnsegundoApellidoChanging(global::System.String value);
        partial void OnsegundoApellidoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cedulaIdentidad
        {
            get
            {
                return _cedulaIdentidad;
            }
            set
            {
                OncedulaIdentidadChanging(value);
                ReportPropertyChanging("cedulaIdentidad");
                _cedulaIdentidad = StructuralObject.SetValidValue(value, false, "cedulaIdentidad");
                ReportPropertyChanged("cedulaIdentidad");
                OncedulaIdentidadChanged();
            }
        }
        private global::System.String _cedulaIdentidad;
        partial void OncedulaIdentidadChanging(global::System.String value);
        partial void OncedulaIdentidadChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String usuarioRegistro
        {
            get
            {
                return _usuarioRegistro;
            }
            set
            {
                OnusuarioRegistroChanging(value);
                ReportPropertyChanging("usuarioRegistro");
                _usuarioRegistro = StructuralObject.SetValidValue(value, false, "usuarioRegistro");
                ReportPropertyChanged("usuarioRegistro");
                OnusuarioRegistroChanged();
            }
        }
        private global::System.String _usuarioRegistro;
        partial void OnusuarioRegistroChanging(global::System.String value);
        partial void OnusuarioRegistroChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fechaRegistro
        {
            get
            {
                return _fechaRegistro;
            }
            set
            {
                OnfechaRegistroChanging(value);
                ReportPropertyChanging("fechaRegistro");
                _fechaRegistro = StructuralObject.SetValidValue(value, "fechaRegistro");
                ReportPropertyChanged("fechaRegistro");
                OnfechaRegistroChanged();
            }
        }
        private global::System.DateTime _fechaRegistro;
        partial void OnfechaRegistroChanging(global::System.DateTime value);
        partial void OnfechaRegistroChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value, "estado");
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.Int16 _estado;
        partial void OnestadoChanging(global::System.Int16 value);
        partial void OnestadoChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LabRestauranteModel", "fk_DetalleFactura_Cliente", "DetalleFactura")]
        public EntityCollection<DetalleFactura> DetalleFactura
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DetalleFactura>("LabRestauranteModel.fk_DetalleFactura_Cliente", "DetalleFactura");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DetalleFactura>("LabRestauranteModel.fk_DetalleFactura_Cliente", "DetalleFactura", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LabRestauranteModel", Name="Comida")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Comida : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Comida.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="precio">Valor inicial de la propiedad precio.</param>
        /// <param name="usuarioRegistro">Valor inicial de la propiedad usuarioRegistro.</param>
        /// <param name="fechaRegistro">Valor inicial de la propiedad fechaRegistro.</param>
        /// <param name="estado">Valor inicial de la propiedad estado.</param>
        public static Comida CreateComida(global::System.Int32 id, global::System.String nombre, global::System.Decimal precio, global::System.String usuarioRegistro, global::System.DateTime fechaRegistro, global::System.Int16 estado)
        {
            Comida comida = new Comida();
            comida.id = id;
            comida.nombre = nombre;
            comida.precio = precio;
            comida.usuarioRegistro = usuarioRegistro;
            comida.fechaRegistro = fechaRegistro;
            comida.estado = estado;
            return comida;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false, "nombre");
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal precio
        {
            get
            {
                return _precio;
            }
            set
            {
                OnprecioChanging(value);
                ReportPropertyChanging("precio");
                _precio = StructuralObject.SetValidValue(value, "precio");
                ReportPropertyChanged("precio");
                OnprecioChanged();
            }
        }
        private global::System.Decimal _precio;
        partial void OnprecioChanging(global::System.Decimal value);
        partial void OnprecioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String usuarioRegistro
        {
            get
            {
                return _usuarioRegistro;
            }
            set
            {
                OnusuarioRegistroChanging(value);
                ReportPropertyChanging("usuarioRegistro");
                _usuarioRegistro = StructuralObject.SetValidValue(value, false, "usuarioRegistro");
                ReportPropertyChanged("usuarioRegistro");
                OnusuarioRegistroChanged();
            }
        }
        private global::System.String _usuarioRegistro;
        partial void OnusuarioRegistroChanging(global::System.String value);
        partial void OnusuarioRegistroChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fechaRegistro
        {
            get
            {
                return _fechaRegistro;
            }
            set
            {
                OnfechaRegistroChanging(value);
                ReportPropertyChanging("fechaRegistro");
                _fechaRegistro = StructuralObject.SetValidValue(value, "fechaRegistro");
                ReportPropertyChanged("fechaRegistro");
                OnfechaRegistroChanged();
            }
        }
        private global::System.DateTime _fechaRegistro;
        partial void OnfechaRegistroChanging(global::System.DateTime value);
        partial void OnfechaRegistroChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value, "estado");
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.Int16 _estado;
        partial void OnestadoChanging(global::System.Int16 value);
        partial void OnestadoChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LabRestauranteModel", "fk_DetalleFactura_Comida", "DetalleFactura")]
        public EntityCollection<DetalleFactura> DetalleFactura
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DetalleFactura>("LabRestauranteModel.fk_DetalleFactura_Comida", "DetalleFactura");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DetalleFactura>("LabRestauranteModel.fk_DetalleFactura_Comida", "DetalleFactura", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LabRestauranteModel", Name="DetalleFactura")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DetalleFactura : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto DetalleFactura.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="idCliente">Valor inicial de la propiedad idCliente.</param>
        /// <param name="idEmpleado">Valor inicial de la propiedad idEmpleado.</param>
        /// <param name="idComida">Valor inicial de la propiedad idComida.</param>
        /// <param name="idBebida">Valor inicial de la propiedad idBebida.</param>
        /// <param name="usuarioRegistro">Valor inicial de la propiedad usuarioRegistro.</param>
        /// <param name="fechaRegistro">Valor inicial de la propiedad fechaRegistro.</param>
        /// <param name="estado">Valor inicial de la propiedad estado.</param>
        public static DetalleFactura CreateDetalleFactura(global::System.Int32 id, global::System.Int32 idCliente, global::System.Int32 idEmpleado, global::System.Int32 idComida, global::System.Int32 idBebida, global::System.String usuarioRegistro, global::System.DateTime fechaRegistro, global::System.Int16 estado)
        {
            DetalleFactura detalleFactura = new DetalleFactura();
            detalleFactura.id = id;
            detalleFactura.idCliente = idCliente;
            detalleFactura.idEmpleado = idEmpleado;
            detalleFactura.idComida = idComida;
            detalleFactura.idBebida = idBebida;
            detalleFactura.usuarioRegistro = usuarioRegistro;
            detalleFactura.fechaRegistro = fechaRegistro;
            detalleFactura.estado = estado;
            return detalleFactura;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idCliente
        {
            get
            {
                return _idCliente;
            }
            set
            {
                OnidClienteChanging(value);
                ReportPropertyChanging("idCliente");
                _idCliente = StructuralObject.SetValidValue(value, "idCliente");
                ReportPropertyChanged("idCliente");
                OnidClienteChanged();
            }
        }
        private global::System.Int32 _idCliente;
        partial void OnidClienteChanging(global::System.Int32 value);
        partial void OnidClienteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idEmpleado
        {
            get
            {
                return _idEmpleado;
            }
            set
            {
                OnidEmpleadoChanging(value);
                ReportPropertyChanging("idEmpleado");
                _idEmpleado = StructuralObject.SetValidValue(value, "idEmpleado");
                ReportPropertyChanged("idEmpleado");
                OnidEmpleadoChanged();
            }
        }
        private global::System.Int32 _idEmpleado;
        partial void OnidEmpleadoChanging(global::System.Int32 value);
        partial void OnidEmpleadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idComida
        {
            get
            {
                return _idComida;
            }
            set
            {
                OnidComidaChanging(value);
                ReportPropertyChanging("idComida");
                _idComida = StructuralObject.SetValidValue(value, "idComida");
                ReportPropertyChanged("idComida");
                OnidComidaChanged();
            }
        }
        private global::System.Int32 _idComida;
        partial void OnidComidaChanging(global::System.Int32 value);
        partial void OnidComidaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idBebida
        {
            get
            {
                return _idBebida;
            }
            set
            {
                OnidBebidaChanging(value);
                ReportPropertyChanging("idBebida");
                _idBebida = StructuralObject.SetValidValue(value, "idBebida");
                ReportPropertyChanged("idBebida");
                OnidBebidaChanged();
            }
        }
        private global::System.Int32 _idBebida;
        partial void OnidBebidaChanging(global::System.Int32 value);
        partial void OnidBebidaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String usuarioRegistro
        {
            get
            {
                return _usuarioRegistro;
            }
            set
            {
                OnusuarioRegistroChanging(value);
                ReportPropertyChanging("usuarioRegistro");
                _usuarioRegistro = StructuralObject.SetValidValue(value, false, "usuarioRegistro");
                ReportPropertyChanged("usuarioRegistro");
                OnusuarioRegistroChanged();
            }
        }
        private global::System.String _usuarioRegistro;
        partial void OnusuarioRegistroChanging(global::System.String value);
        partial void OnusuarioRegistroChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fechaRegistro
        {
            get
            {
                return _fechaRegistro;
            }
            set
            {
                OnfechaRegistroChanging(value);
                ReportPropertyChanging("fechaRegistro");
                _fechaRegistro = StructuralObject.SetValidValue(value, "fechaRegistro");
                ReportPropertyChanged("fechaRegistro");
                OnfechaRegistroChanged();
            }
        }
        private global::System.DateTime _fechaRegistro;
        partial void OnfechaRegistroChanging(global::System.DateTime value);
        partial void OnfechaRegistroChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value, "estado");
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.Int16 _estado;
        partial void OnestadoChanging(global::System.Int16 value);
        partial void OnestadoChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LabRestauranteModel", "fk_DetalleFactura_Bebida", "Bebida")]
        public Bebida Bebida
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bebida>("LabRestauranteModel.fk_DetalleFactura_Bebida", "Bebida").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bebida>("LabRestauranteModel.fk_DetalleFactura_Bebida", "Bebida").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Bebida> BebidaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Bebida>("LabRestauranteModel.fk_DetalleFactura_Bebida", "Bebida");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Bebida>("LabRestauranteModel.fk_DetalleFactura_Bebida", "Bebida", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LabRestauranteModel", "fk_DetalleFactura_Cliente", "Cliente")]
        public Cliente Cliente
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("LabRestauranteModel.fk_DetalleFactura_Cliente", "Cliente").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("LabRestauranteModel.fk_DetalleFactura_Cliente", "Cliente").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Cliente> ClienteReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Cliente>("LabRestauranteModel.fk_DetalleFactura_Cliente", "Cliente");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Cliente>("LabRestauranteModel.fk_DetalleFactura_Cliente", "Cliente", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LabRestauranteModel", "fk_DetalleFactura_Comida", "Comida")]
        public Comida Comida
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Comida>("LabRestauranteModel.fk_DetalleFactura_Comida", "Comida").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Comida>("LabRestauranteModel.fk_DetalleFactura_Comida", "Comida").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Comida> ComidaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Comida>("LabRestauranteModel.fk_DetalleFactura_Comida", "Comida");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Comida>("LabRestauranteModel.fk_DetalleFactura_Comida", "Comida", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LabRestauranteModel", "fk_DetalleFactura_Empleado", "Empleado")]
        public Empleado Empleado
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Empleado>("LabRestauranteModel.fk_DetalleFactura_Empleado", "Empleado").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Empleado>("LabRestauranteModel.fk_DetalleFactura_Empleado", "Empleado").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Empleado> EmpleadoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Empleado>("LabRestauranteModel.fk_DetalleFactura_Empleado", "Empleado");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Empleado>("LabRestauranteModel.fk_DetalleFactura_Empleado", "Empleado", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LabRestauranteModel", Name="Empleado")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Empleado : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Empleado.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="primerApellido">Valor inicial de la propiedad primerApellido.</param>
        /// <param name="segundoApellido">Valor inicial de la propiedad segundoApellido.</param>
        /// <param name="telefono">Valor inicial de la propiedad telefono.</param>
        /// <param name="direccion">Valor inicial de la propiedad direccion.</param>
        /// <param name="cargo">Valor inicial de la propiedad cargo.</param>
        /// <param name="usuarioRegistro">Valor inicial de la propiedad usuarioRegistro.</param>
        /// <param name="fechaRegistro">Valor inicial de la propiedad fechaRegistro.</param>
        /// <param name="estado">Valor inicial de la propiedad estado.</param>
        public static Empleado CreateEmpleado(global::System.Int32 id, global::System.String nombre, global::System.String primerApellido, global::System.String segundoApellido, global::System.Int64 telefono, global::System.String direccion, global::System.String cargo, global::System.String usuarioRegistro, global::System.DateTime fechaRegistro, global::System.Int16 estado)
        {
            Empleado empleado = new Empleado();
            empleado.id = id;
            empleado.nombre = nombre;
            empleado.primerApellido = primerApellido;
            empleado.segundoApellido = segundoApellido;
            empleado.telefono = telefono;
            empleado.direccion = direccion;
            empleado.cargo = cargo;
            empleado.usuarioRegistro = usuarioRegistro;
            empleado.fechaRegistro = fechaRegistro;
            empleado.estado = estado;
            return empleado;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false, "nombre");
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String primerApellido
        {
            get
            {
                return _primerApellido;
            }
            set
            {
                OnprimerApellidoChanging(value);
                ReportPropertyChanging("primerApellido");
                _primerApellido = StructuralObject.SetValidValue(value, false, "primerApellido");
                ReportPropertyChanged("primerApellido");
                OnprimerApellidoChanged();
            }
        }
        private global::System.String _primerApellido;
        partial void OnprimerApellidoChanging(global::System.String value);
        partial void OnprimerApellidoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String segundoApellido
        {
            get
            {
                return _segundoApellido;
            }
            set
            {
                OnsegundoApellidoChanging(value);
                ReportPropertyChanging("segundoApellido");
                _segundoApellido = StructuralObject.SetValidValue(value, false, "segundoApellido");
                ReportPropertyChanged("segundoApellido");
                OnsegundoApellidoChanged();
            }
        }
        private global::System.String _segundoApellido;
        partial void OnsegundoApellidoChanging(global::System.String value);
        partial void OnsegundoApellidoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 telefono
        {
            get
            {
                return _telefono;
            }
            set
            {
                OntelefonoChanging(value);
                ReportPropertyChanging("telefono");
                _telefono = StructuralObject.SetValidValue(value, "telefono");
                ReportPropertyChanged("telefono");
                OntelefonoChanged();
            }
        }
        private global::System.Int64 _telefono;
        partial void OntelefonoChanging(global::System.Int64 value);
        partial void OntelefonoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String direccion
        {
            get
            {
                return _direccion;
            }
            set
            {
                OndireccionChanging(value);
                ReportPropertyChanging("direccion");
                _direccion = StructuralObject.SetValidValue(value, false, "direccion");
                ReportPropertyChanged("direccion");
                OndireccionChanged();
            }
        }
        private global::System.String _direccion;
        partial void OndireccionChanging(global::System.String value);
        partial void OndireccionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String cargo
        {
            get
            {
                return _cargo;
            }
            set
            {
                OncargoChanging(value);
                ReportPropertyChanging("cargo");
                _cargo = StructuralObject.SetValidValue(value, false, "cargo");
                ReportPropertyChanged("cargo");
                OncargoChanged();
            }
        }
        private global::System.String _cargo;
        partial void OncargoChanging(global::System.String value);
        partial void OncargoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String usuarioRegistro
        {
            get
            {
                return _usuarioRegistro;
            }
            set
            {
                OnusuarioRegistroChanging(value);
                ReportPropertyChanging("usuarioRegistro");
                _usuarioRegistro = StructuralObject.SetValidValue(value, false, "usuarioRegistro");
                ReportPropertyChanged("usuarioRegistro");
                OnusuarioRegistroChanged();
            }
        }
        private global::System.String _usuarioRegistro;
        partial void OnusuarioRegistroChanging(global::System.String value);
        partial void OnusuarioRegistroChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fechaRegistro
        {
            get
            {
                return _fechaRegistro;
            }
            set
            {
                OnfechaRegistroChanging(value);
                ReportPropertyChanging("fechaRegistro");
                _fechaRegistro = StructuralObject.SetValidValue(value, "fechaRegistro");
                ReportPropertyChanged("fechaRegistro");
                OnfechaRegistroChanged();
            }
        }
        private global::System.DateTime _fechaRegistro;
        partial void OnfechaRegistroChanging(global::System.DateTime value);
        partial void OnfechaRegistroChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value, "estado");
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.Int16 _estado;
        partial void OnestadoChanging(global::System.Int16 value);
        partial void OnestadoChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LabRestauranteModel", "fk_DetalleFactura_Empleado", "DetalleFactura")]
        public EntityCollection<DetalleFactura> DetalleFactura
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<DetalleFactura>("LabRestauranteModel.fk_DetalleFactura_Empleado", "DetalleFactura");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<DetalleFactura>("LabRestauranteModel.fk_DetalleFactura_Empleado", "DetalleFactura", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LabRestauranteModel", "fk_Usuario_Empleado", "Usuario")]
        public EntityCollection<Usuario> Usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Usuario>("LabRestauranteModel.fk_Usuario_Empleado", "Usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Usuario>("LabRestauranteModel.fk_Usuario_Empleado", "Usuario", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LabRestauranteModel", Name="Usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Usuario : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Usuario.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="clave">Valor inicial de la propiedad clave.</param>
        /// <param name="idEmpleado">Valor inicial de la propiedad idEmpleado.</param>
        /// <param name="usuarioRegistro">Valor inicial de la propiedad usuarioRegistro.</param>
        /// <param name="fechaRegistro">Valor inicial de la propiedad fechaRegistro.</param>
        /// <param name="estado">Valor inicial de la propiedad estado.</param>
        public static Usuario CreateUsuario(global::System.Int32 id, global::System.String nombre, global::System.String clave, global::System.Int32 idEmpleado, global::System.String usuarioRegistro, global::System.DateTime fechaRegistro, global::System.Int16 estado)
        {
            Usuario usuario = new Usuario();
            usuario.id = id;
            usuario.nombre = nombre;
            usuario.clave = clave;
            usuario.idEmpleado = idEmpleado;
            usuario.usuarioRegistro = usuarioRegistro;
            usuario.fechaRegistro = fechaRegistro;
            usuario.estado = estado;
            return usuario;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, "id");
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false, "nombre");
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String clave
        {
            get
            {
                return _clave;
            }
            set
            {
                OnclaveChanging(value);
                ReportPropertyChanging("clave");
                _clave = StructuralObject.SetValidValue(value, false, "clave");
                ReportPropertyChanged("clave");
                OnclaveChanged();
            }
        }
        private global::System.String _clave;
        partial void OnclaveChanging(global::System.String value);
        partial void OnclaveChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idEmpleado
        {
            get
            {
                return _idEmpleado;
            }
            set
            {
                OnidEmpleadoChanging(value);
                ReportPropertyChanging("idEmpleado");
                _idEmpleado = StructuralObject.SetValidValue(value, "idEmpleado");
                ReportPropertyChanged("idEmpleado");
                OnidEmpleadoChanged();
            }
        }
        private global::System.Int32 _idEmpleado;
        partial void OnidEmpleadoChanging(global::System.Int32 value);
        partial void OnidEmpleadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String usuarioRegistro
        {
            get
            {
                return _usuarioRegistro;
            }
            set
            {
                OnusuarioRegistroChanging(value);
                ReportPropertyChanging("usuarioRegistro");
                _usuarioRegistro = StructuralObject.SetValidValue(value, false, "usuarioRegistro");
                ReportPropertyChanged("usuarioRegistro");
                OnusuarioRegistroChanged();
            }
        }
        private global::System.String _usuarioRegistro;
        partial void OnusuarioRegistroChanging(global::System.String value);
        partial void OnusuarioRegistroChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime fechaRegistro
        {
            get
            {
                return _fechaRegistro;
            }
            set
            {
                OnfechaRegistroChanging(value);
                ReportPropertyChanging("fechaRegistro");
                _fechaRegistro = StructuralObject.SetValidValue(value, "fechaRegistro");
                ReportPropertyChanged("fechaRegistro");
                OnfechaRegistroChanged();
            }
        }
        private global::System.DateTime _fechaRegistro;
        partial void OnfechaRegistroChanging(global::System.DateTime value);
        partial void OnfechaRegistroChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value, "estado");
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.Int16 _estado;
        partial void OnestadoChanging(global::System.Int16 value);
        partial void OnestadoChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LabRestauranteModel", "fk_Usuario_Empleado", "Empleado")]
        public Empleado Empleado
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Empleado>("LabRestauranteModel.fk_Usuario_Empleado", "Empleado").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Empleado>("LabRestauranteModel.fk_Usuario_Empleado", "Empleado").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Empleado> EmpleadoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Empleado>("LabRestauranteModel.fk_Usuario_Empleado", "Empleado");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Empleado>("LabRestauranteModel.fk_Usuario_Empleado", "Empleado", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
